//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTE.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class vi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal vi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdminLTE.Resources.vi", typeof(vi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin địa điểm.
        /// </summary>
        internal static string fDiaDiem {
            get {
                return ResourceManager.GetString("fDiaDiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới Chức năng.
        /// </summary>
        internal static string fSysFunctionAdd {
            get {
                return ResourceManager.GetString("fSysFunctionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa Chức năng.
        /// </summary>
        internal static string fSysFunctionEdit {
            get {
                return ResourceManager.GetString("fSysFunctionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới Page hệ thống.
        /// </summary>
        internal static string fSysPageAdd {
            get {
                return ResourceManager.GetString("fSysPageAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa Page hệ thống.
        /// </summary>
        internal static string fSysPageEdit {
            get {
                return ResourceManager.GetString("fSysPageEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin xe.
        /// </summary>
        internal static string fXe {
            get {
                return ResourceManager.GetString("fXe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu.
        /// </summary>
        internal static string KHONG_CO_DU_LIEU {
            get {
                return ResourceManager.GetString("KHONG_CO_DU_LIEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật và xuất bản.
        /// </summary>
        internal static string UpdateAndPublishing {
            get {
                return ResourceManager.GetString("UpdateAndPublishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật và hủy xuất bản.
        /// </summary>
        internal static string UpdateUnPublish {
            get {
                return ResourceManager.GetString("UpdateUnPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ Phận đề nghị.
        /// </summary>
        internal static string viewBoPhanDeNghi {
            get {
                return ResourceManager.GetString("viewBoPhanDeNghi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách chuyên mục.
        /// </summary>
        internal static string viewCategorylist {
            get {
                return ResourceManager.GetString("viewCategorylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục địa điểm.
        /// </summary>
        internal static string viewDiaDiem {
            get {
                return ResourceManager.GetString("viewDiaDiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng hệ thống.
        /// </summary>
        internal static string viewFunctionList {
            get {
                return ResourceManager.GetString("viewFunctionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách chuyên mục ảnh.
        /// </summary>
        internal static string viewImageCategoryList {
            get {
                return ResourceManager.GetString("viewImageCategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách menu.
        /// </summary>
        internal static string viewMenu {
            get {
                return ResourceManager.GetString("viewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tin tức.
        /// </summary>
        internal static string viewNewsList {
            get {
                return ResourceManager.GetString("viewNewsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm người dùng.
        /// </summary>
        internal static string viewSysGroup {
            get {
                return ResourceManager.GetString("viewSysGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page hệ thống.
        /// </summary>
        internal static string ViewSysPage {
            get {
                return ResourceManager.GetString("ViewSysPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page đơn vị.
        /// </summary>
        internal static string viewSysUnit {
            get {
                return ResourceManager.GetString("viewSysUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách chuyên mục video.
        /// </summary>
        internal static string viewVideoCategoryList {
            get {
                return ResourceManager.GetString("viewVideoCategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách xe đưa đón cán bộ nhân viên.
        /// </summary>
        internal static string viewXe {
            get {
                return ResourceManager.GetString("viewXe", resourceCulture);
            }
        }
    }
}
