//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PvnEN.Web.sites.en.Pages {
    
    
    public partial class _default {
        
        /// <summary>
        /// ucPanoSlideFullWidth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PvnEN.Web.Usercontrols_EN.ucPanoSlideFullWidth ucPanoSlideFullWidth;
        
        /// <summary>
        /// ucAboutMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PvnEN.Web.Usercontrols_EN.ucAboutMain ucAboutMain;
        
        /// <summary>
        /// ucProductMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PvnEN.Web.Usercontrols_EN.ucProductMain ucProductMain;
        
        /// <summary>
        /// ucNewsListMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PvnEN.Web.Usercontrols_EN.ucNewsListMain ucNewsListMain;
    }
}
